// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type ConnectionIcebergUpdateType string

const (
	ConnectionIcebergUpdateTypeIceberg ConnectionIcebergUpdateType = "ICEBERG"
)

func (e ConnectionIcebergUpdateType) ToPointer() *ConnectionIcebergUpdateType {
	return &e
}

func (e *ConnectionIcebergUpdateType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ICEBERG":
		*e = ConnectionIcebergUpdateType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ConnectionIcebergUpdateType: %v", v)
	}
}

type ConnectionIcebergUpdate struct {
	// Whether this connection should be marked as active.
	Active *bool                        `json:"active,omitempty"`
	Type   *ConnectionIcebergUpdateType `json:"type"`
	// The unique name of this connection.
	Name *string `json:"name,omitempty"`
	// The update schedule defines when Etleap should automatically check the source for new data. See <a href= "https://support.etleap.com/hc/en-us/articles/360019768853-What-is-the-difference-between-a-Refresh-and-an-Update-" target="_blank" rel="noopener">Updates &amp; Refreshes</a> for more information. When undefined, the pipeline will default to the schedule set on the source connection.
	UpdateSchedule      *UpdateScheduleTypes `json:"updateSchedule,omitempty"`
	IamRole             *string              `json:"iamRole,omitempty"`
	WarehouseConnection *string              `json:"warehouseConnection,omitempty"`
	GlueDatabase        *string              `json:"glueDatabase,omitempty"`
	BaseDirectory       *string              `json:"baseDirectory,omitempty"`
	DataBucket          *string              `json:"dataBucket,omitempty"`
	GlueRegion          *string              `json:"glueRegion,omitempty"`
}

func (o *ConnectionIcebergUpdate) GetActive() *bool {
	if o == nil {
		return nil
	}
	return o.Active
}

func (o *ConnectionIcebergUpdate) GetType() *ConnectionIcebergUpdateType {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *ConnectionIcebergUpdate) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *ConnectionIcebergUpdate) GetUpdateSchedule() *UpdateScheduleTypes {
	if o == nil {
		return nil
	}
	return o.UpdateSchedule
}

func (o *ConnectionIcebergUpdate) GetUpdateScheduleMonthly() *UpdateScheduleModeMonthly {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeMonthly
	}
	return nil
}

func (o *ConnectionIcebergUpdate) GetUpdateScheduleHourly() *UpdateScheduleModeHourly {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeHourly
	}
	return nil
}

func (o *ConnectionIcebergUpdate) GetUpdateScheduleInterval() *UpdateScheduleModeInterval {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeInterval
	}
	return nil
}

func (o *ConnectionIcebergUpdate) GetUpdateScheduleDaily() *UpdateScheduleModeDaily {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeDaily
	}
	return nil
}

func (o *ConnectionIcebergUpdate) GetUpdateScheduleWeekly() *UpdateScheduleModeWeekly {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeWeekly
	}
	return nil
}

func (o *ConnectionIcebergUpdate) GetIamRole() *string {
	if o == nil {
		return nil
	}
	return o.IamRole
}

func (o *ConnectionIcebergUpdate) GetWarehouseConnection() *string {
	if o == nil {
		return nil
	}
	return o.WarehouseConnection
}

func (o *ConnectionIcebergUpdate) GetGlueDatabase() *string {
	if o == nil {
		return nil
	}
	return o.GlueDatabase
}

func (o *ConnectionIcebergUpdate) GetBaseDirectory() *string {
	if o == nil {
		return nil
	}
	return o.BaseDirectory
}

func (o *ConnectionIcebergUpdate) GetDataBucket() *string {
	if o == nil {
		return nil
	}
	return o.DataBucket
}

func (o *ConnectionIcebergUpdate) GetGlueRegion() *string {
	if o == nil {
		return nil
	}
	return o.GlueRegion
}
