// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/etleap/terraform-provider-etleap/internal/sdk/pkg/utils"
	"time"
)

type ConnectionZendeskType string

const (
	ConnectionZendeskTypeZendesk ConnectionZendeskType = "ZENDESK"
)

func (e ConnectionZendeskType) ToPointer() *ConnectionZendeskType {
	return &e
}

func (e *ConnectionZendeskType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ZENDESK":
		*e = ConnectionZendeskType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ConnectionZendeskType: %v", v)
	}
}

// ConnectionZendeskStatus - The current status of the connection.
type ConnectionZendeskStatus string

const (
	ConnectionZendeskStatusUnknown     ConnectionZendeskStatus = "UNKNOWN"
	ConnectionZendeskStatusUp          ConnectionZendeskStatus = "UP"
	ConnectionZendeskStatusDown        ConnectionZendeskStatus = "DOWN"
	ConnectionZendeskStatusResize      ConnectionZendeskStatus = "RESIZE"
	ConnectionZendeskStatusMaintenance ConnectionZendeskStatus = "MAINTENANCE"
	ConnectionZendeskStatusQuota       ConnectionZendeskStatus = "QUOTA"
	ConnectionZendeskStatusCreating    ConnectionZendeskStatus = "CREATING"
)

func (e ConnectionZendeskStatus) ToPointer() *ConnectionZendeskStatus {
	return &e
}

func (e *ConnectionZendeskStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "UNKNOWN":
		fallthrough
	case "UP":
		fallthrough
	case "DOWN":
		fallthrough
	case "RESIZE":
		fallthrough
	case "MAINTENANCE":
		fallthrough
	case "QUOTA":
		fallthrough
	case "CREATING":
		*e = ConnectionZendeskStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ConnectionZendeskStatus: %v", v)
	}
}

type ConnectionZendesk struct {
	// The unique identifier of the connection.
	ID string `json:"id"`
	// The unique name of this connection.
	Name string                `json:"name"`
	Type ConnectionZendeskType `json:"type"`
	// Whether this connection has been marked as active.
	Active bool `json:"active"`
	// The current status of the connection.
	Status ConnectionZendeskStatus `json:"status"`
	// The date and time when then the connection was created.
	CreateDate time.Time `json:"createDate"`
	// The name of the subdomain. This is in the URL when you use zendesk: [subdomain].zendesk.com
	Subdomain string `json:"subdomain"`
	Username  string `json:"username"`
}

func (c ConnectionZendesk) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConnectionZendesk) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *ConnectionZendesk) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ConnectionZendesk) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ConnectionZendesk) GetType() ConnectionZendeskType {
	if o == nil {
		return ConnectionZendeskType("")
	}
	return o.Type
}

func (o *ConnectionZendesk) GetActive() bool {
	if o == nil {
		return false
	}
	return o.Active
}

func (o *ConnectionZendesk) GetStatus() ConnectionZendeskStatus {
	if o == nil {
		return ConnectionZendeskStatus("")
	}
	return o.Status
}

func (o *ConnectionZendesk) GetCreateDate() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreateDate
}

func (o *ConnectionZendesk) GetSubdomain() string {
	if o == nil {
		return ""
	}
	return o.Subdomain
}

func (o *ConnectionZendesk) GetUsername() string {
	if o == nil {
		return ""
	}
	return o.Username
}

type ConnectionZendeskInput struct {
	// The unique name of this connection.
	Name string                `json:"name"`
	Type ConnectionZendeskType `json:"type"`
	// Code retrieved from `/connections/oauth2-initiation`. **Note:** it is short-lived, therefore the connection creation should be done as soon as code is returned.
	Code string `json:"code"`
	// The name of the subdomain. This is in the URL when you use zendesk: [subdomain].zendesk.com
	Subdomain string `json:"subdomain"`
}

func (o *ConnectionZendeskInput) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ConnectionZendeskInput) GetType() ConnectionZendeskType {
	if o == nil {
		return ConnectionZendeskType("")
	}
	return o.Type
}

func (o *ConnectionZendeskInput) GetCode() string {
	if o == nil {
		return ""
	}
	return o.Code
}

func (o *ConnectionZendeskInput) GetSubdomain() string {
	if o == nil {
		return ""
	}
	return o.Subdomain
}
