// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/etleap/terraform-provider-etleap/internal/sdk/pkg/utils"
	"time"
)

type ConnectionTwitterAdsType string

const (
	ConnectionTwitterAdsTypeTwitterAds ConnectionTwitterAdsType = "TWITTER_ADS"
)

func (e ConnectionTwitterAdsType) ToPointer() *ConnectionTwitterAdsType {
	return &e
}

func (e *ConnectionTwitterAdsType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "TWITTER_ADS":
		*e = ConnectionTwitterAdsType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ConnectionTwitterAdsType: %v", v)
	}
}

// ConnectionTwitterAdsStatus - The current status of the connection.
type ConnectionTwitterAdsStatus string

const (
	ConnectionTwitterAdsStatusUnknown     ConnectionTwitterAdsStatus = "UNKNOWN"
	ConnectionTwitterAdsStatusUp          ConnectionTwitterAdsStatus = "UP"
	ConnectionTwitterAdsStatusDown        ConnectionTwitterAdsStatus = "DOWN"
	ConnectionTwitterAdsStatusResize      ConnectionTwitterAdsStatus = "RESIZE"
	ConnectionTwitterAdsStatusMaintenance ConnectionTwitterAdsStatus = "MAINTENANCE"
	ConnectionTwitterAdsStatusQuota       ConnectionTwitterAdsStatus = "QUOTA"
	ConnectionTwitterAdsStatusCreating    ConnectionTwitterAdsStatus = "CREATING"
)

func (e ConnectionTwitterAdsStatus) ToPointer() *ConnectionTwitterAdsStatus {
	return &e
}

func (e *ConnectionTwitterAdsStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "UNKNOWN":
		fallthrough
	case "UP":
		fallthrough
	case "DOWN":
		fallthrough
	case "RESIZE":
		fallthrough
	case "MAINTENANCE":
		fallthrough
	case "QUOTA":
		fallthrough
	case "CREATING":
		*e = ConnectionTwitterAdsStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ConnectionTwitterAdsStatus: %v", v)
	}
}

type ConnectionTwitterAdsDefaultUpdateSchedule struct {
	// The pipeline mode refers to how the pipeline fetches data changes from the source and how those changes are applied to the destination table. See <a target="_blank" href="https://docs.etleap.com/documentation/pipeline/modes/introduction/">the documentation</a> for more details.
	PipelineMode *PipelineUpdateModes `json:"pipelineMode,omitempty"`
	// The update schedule defines when Etleap should automatically check the source for new data. See <a href= "https://support.etleap.com/hc/en-us/articles/360019768853-What-is-the-difference-between-a-Refresh-and-an-Update-" target="_blank" rel="noopener">Updates &amp; Refreshes</a> for more information. When undefined, the pipeline will default to the schedule set on the source connection.
	UpdateSchedule *UpdateScheduleTypes `json:"updateSchedule,omitempty"`
}

func (o *ConnectionTwitterAdsDefaultUpdateSchedule) GetPipelineMode() *PipelineUpdateModes {
	if o == nil {
		return nil
	}
	return o.PipelineMode
}

func (o *ConnectionTwitterAdsDefaultUpdateSchedule) GetUpdateSchedule() *UpdateScheduleTypes {
	if o == nil {
		return nil
	}
	return o.UpdateSchedule
}

func (o *ConnectionTwitterAdsDefaultUpdateSchedule) GetUpdateScheduleInterval() *UpdateScheduleModeInterval {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeInterval
	}
	return nil
}

func (o *ConnectionTwitterAdsDefaultUpdateSchedule) GetUpdateScheduleHourly() *UpdateScheduleModeHourly {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeHourly
	}
	return nil
}

func (o *ConnectionTwitterAdsDefaultUpdateSchedule) GetUpdateScheduleDaily() *UpdateScheduleModeDaily {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeDaily
	}
	return nil
}

func (o *ConnectionTwitterAdsDefaultUpdateSchedule) GetUpdateScheduleWeekly() *UpdateScheduleModeWeekly {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeWeekly
	}
	return nil
}

func (o *ConnectionTwitterAdsDefaultUpdateSchedule) GetUpdateScheduleMonthly() *UpdateScheduleModeMonthly {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeMonthly
	}
	return nil
}

type ConnectionTwitterAds struct {
	// The unique identifier of the connection.
	ID string `json:"id"`
	// The unique name of this connection.
	Name string                   `json:"name"`
	Type ConnectionTwitterAdsType `json:"type"`
	// Whether this connection has been marked as active.
	Active bool `json:"active"`
	// The current status of the connection.
	Status ConnectionTwitterAdsStatus `json:"status"`
	// The date and time when then the connection was created.
	CreateDate time.Time `json:"createDate"`
	// The update schedule defines when Etleap should automatically check the source for new data. See <a href= "https://support.etleap.com/hc/en-us/articles/360019768853-What-is-the-difference-between-a-Refresh-and-an-Update-" target="_blank" rel="noopener">Updates &amp; Refreshes</a> for more information. When undefined, the pipeline will default to the schedule set on the source connection.
	UpdateSchedule *UpdateScheduleTypes `json:"updateSchedule,omitempty"`
	// When an update schedule is not defined for a connection, the default schedule is used. The default defined individually per `pipelineMode` and may be subject to change.
	DefaultUpdateSchedule []ConnectionTwitterAdsDefaultUpdateSchedule `json:"defaultUpdateSchedule"`
	// This represents your X developer app when making API requests. Generated under 'Consumer API keys'.
	AppKey string `json:"appKey"`
	// If you want to create pipelines from entities that uses X API V2 endpoints you need to specify which X accounts you want to retrieve data from. The usernames must be separated by comma and without the @
	TwitterUsernames *string `json:"twitterUsernames,omitempty"`
}

func (c ConnectionTwitterAds) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConnectionTwitterAds) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ConnectionTwitterAds) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ConnectionTwitterAds) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ConnectionTwitterAds) GetType() ConnectionTwitterAdsType {
	if o == nil {
		return ConnectionTwitterAdsType("")
	}
	return o.Type
}

func (o *ConnectionTwitterAds) GetActive() bool {
	if o == nil {
		return false
	}
	return o.Active
}

func (o *ConnectionTwitterAds) GetStatus() ConnectionTwitterAdsStatus {
	if o == nil {
		return ConnectionTwitterAdsStatus("")
	}
	return o.Status
}

func (o *ConnectionTwitterAds) GetCreateDate() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreateDate
}

func (o *ConnectionTwitterAds) GetUpdateSchedule() *UpdateScheduleTypes {
	if o == nil {
		return nil
	}
	return o.UpdateSchedule
}

func (o *ConnectionTwitterAds) GetUpdateScheduleInterval() *UpdateScheduleModeInterval {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeInterval
	}
	return nil
}

func (o *ConnectionTwitterAds) GetUpdateScheduleHourly() *UpdateScheduleModeHourly {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeHourly
	}
	return nil
}

func (o *ConnectionTwitterAds) GetUpdateScheduleDaily() *UpdateScheduleModeDaily {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeDaily
	}
	return nil
}

func (o *ConnectionTwitterAds) GetUpdateScheduleWeekly() *UpdateScheduleModeWeekly {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeWeekly
	}
	return nil
}

func (o *ConnectionTwitterAds) GetUpdateScheduleMonthly() *UpdateScheduleModeMonthly {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeMonthly
	}
	return nil
}

func (o *ConnectionTwitterAds) GetDefaultUpdateSchedule() []ConnectionTwitterAdsDefaultUpdateSchedule {
	if o == nil {
		return []ConnectionTwitterAdsDefaultUpdateSchedule{}
	}
	return o.DefaultUpdateSchedule
}

func (o *ConnectionTwitterAds) GetAppKey() string {
	if o == nil {
		return ""
	}
	return o.AppKey
}

func (o *ConnectionTwitterAds) GetTwitterUsernames() *string {
	if o == nil {
		return nil
	}
	return o.TwitterUsernames
}

type ConnectionTwitterAdsInput struct {
	// The unique name of this connection.
	Name string                   `json:"name"`
	Type ConnectionTwitterAdsType `json:"type"`
	// The update schedule defines when Etleap should automatically check the source for new data. See <a href= "https://support.etleap.com/hc/en-us/articles/360019768853-What-is-the-difference-between-a-Refresh-and-an-Update-" target="_blank" rel="noopener">Updates &amp; Refreshes</a> for more information. When undefined, the pipeline will default to the schedule set on the source connection.
	UpdateSchedule *UpdateScheduleTypes `json:"updateSchedule,omitempty"`
	// This represents your X developer app when making API requests. Generated under 'Consumer API keys'.
	AppKey string `json:"appKey"`
	// This authenticates your X developer app when making API requests. Generated under 'Consumer API keys'.
	AppSecretKey string `json:"appSecretKey"`
	// This identifies your X account when generating Ad reports. Generated under 'Access token & access token secret'.
	AccessToken string `json:"accessToken"`
	// This authenticates your X account when generating Ad reports. Generated under 'Access token & access token secret'.
	AccessTokenSecret string `json:"accessTokenSecret"`
	// If you want to create pipelines from entities that uses X API V2 endpoints you need to specify which X accounts you want to retrieve data from. The usernames must be separated by comma and without the @
	TwitterUsernames *string `json:"twitterUsernames,omitempty"`
}

func (o *ConnectionTwitterAdsInput) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ConnectionTwitterAdsInput) GetType() ConnectionTwitterAdsType {
	if o == nil {
		return ConnectionTwitterAdsType("")
	}
	return o.Type
}

func (o *ConnectionTwitterAdsInput) GetUpdateSchedule() *UpdateScheduleTypes {
	if o == nil {
		return nil
	}
	return o.UpdateSchedule
}

func (o *ConnectionTwitterAdsInput) GetUpdateScheduleInterval() *UpdateScheduleModeInterval {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeInterval
	}
	return nil
}

func (o *ConnectionTwitterAdsInput) GetUpdateScheduleHourly() *UpdateScheduleModeHourly {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeHourly
	}
	return nil
}

func (o *ConnectionTwitterAdsInput) GetUpdateScheduleDaily() *UpdateScheduleModeDaily {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeDaily
	}
	return nil
}

func (o *ConnectionTwitterAdsInput) GetUpdateScheduleWeekly() *UpdateScheduleModeWeekly {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeWeekly
	}
	return nil
}

func (o *ConnectionTwitterAdsInput) GetUpdateScheduleMonthly() *UpdateScheduleModeMonthly {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeMonthly
	}
	return nil
}

func (o *ConnectionTwitterAdsInput) GetAppKey() string {
	if o == nil {
		return ""
	}
	return o.AppKey
}

func (o *ConnectionTwitterAdsInput) GetAppSecretKey() string {
	if o == nil {
		return ""
	}
	return o.AppSecretKey
}

func (o *ConnectionTwitterAdsInput) GetAccessToken() string {
	if o == nil {
		return ""
	}
	return o.AccessToken
}

func (o *ConnectionTwitterAdsInput) GetAccessTokenSecret() string {
	if o == nil {
		return ""
	}
	return o.AccessTokenSecret
}

func (o *ConnectionTwitterAdsInput) GetTwitterUsernames() *string {
	if o == nil {
		return nil
	}
	return o.TwitterUsernames
}
