// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/etleap/terraform-provider-etleap/internal/sdk/pkg/utils"
	"time"
)

type ConnectionHubspotType string

const (
	ConnectionHubspotTypeHubspot ConnectionHubspotType = "HUBSPOT"
)

func (e ConnectionHubspotType) ToPointer() *ConnectionHubspotType {
	return &e
}

func (e *ConnectionHubspotType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "HUBSPOT":
		*e = ConnectionHubspotType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ConnectionHubspotType: %v", v)
	}
}

// ConnectionHubspotStatus - The current status of the connection.
type ConnectionHubspotStatus string

const (
	ConnectionHubspotStatusUnknown     ConnectionHubspotStatus = "UNKNOWN"
	ConnectionHubspotStatusUp          ConnectionHubspotStatus = "UP"
	ConnectionHubspotStatusDown        ConnectionHubspotStatus = "DOWN"
	ConnectionHubspotStatusResize      ConnectionHubspotStatus = "RESIZE"
	ConnectionHubspotStatusMaintenance ConnectionHubspotStatus = "MAINTENANCE"
	ConnectionHubspotStatusQuota       ConnectionHubspotStatus = "QUOTA"
	ConnectionHubspotStatusCreating    ConnectionHubspotStatus = "CREATING"
)

func (e ConnectionHubspotStatus) ToPointer() *ConnectionHubspotStatus {
	return &e
}

func (e *ConnectionHubspotStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "UNKNOWN":
		fallthrough
	case "UP":
		fallthrough
	case "DOWN":
		fallthrough
	case "RESIZE":
		fallthrough
	case "MAINTENANCE":
		fallthrough
	case "QUOTA":
		fallthrough
	case "CREATING":
		*e = ConnectionHubspotStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ConnectionHubspotStatus: %v", v)
	}
}

type ConnectionHubspot struct {
	// The unique identifier of the connection.
	ID string `json:"id"`
	// The unique name of this connection.
	Name string                `json:"name"`
	Type ConnectionHubspotType `json:"type"`
	// Whether this connection has been marked as active.
	Active bool `json:"active"`
	// The current status of the connection.
	Status ConnectionHubspotStatus `json:"status"`
	// The date and time when then the connection was created.
	CreateDate time.Time `json:"createDate"`
	Username   string    `json:"username"`
	HubID      int64     `json:"hubId"`
}

func (c ConnectionHubspot) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConnectionHubspot) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *ConnectionHubspot) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ConnectionHubspot) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ConnectionHubspot) GetType() ConnectionHubspotType {
	if o == nil {
		return ConnectionHubspotType("")
	}
	return o.Type
}

func (o *ConnectionHubspot) GetActive() bool {
	if o == nil {
		return false
	}
	return o.Active
}

func (o *ConnectionHubspot) GetStatus() ConnectionHubspotStatus {
	if o == nil {
		return ConnectionHubspotStatus("")
	}
	return o.Status
}

func (o *ConnectionHubspot) GetCreateDate() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreateDate
}

func (o *ConnectionHubspot) GetUsername() string {
	if o == nil {
		return ""
	}
	return o.Username
}

func (o *ConnectionHubspot) GetHubID() int64 {
	if o == nil {
		return 0
	}
	return o.HubID
}

type ConnectionHubspotInput struct {
	// The unique name of this connection.
	Name string                `json:"name"`
	Type ConnectionHubspotType `json:"type"`
	// Code retrieved from `/connections/oauth2-initiation`. **Note:** it is short-lived, therefore the connection creation should be done as soon as code is returned.
	Code string `json:"code"`
}

func (o *ConnectionHubspotInput) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ConnectionHubspotInput) GetType() ConnectionHubspotType {
	if o == nil {
		return ConnectionHubspotType("")
	}
	return o.Type
}

func (o *ConnectionHubspotInput) GetCode() string {
	if o == nil {
		return ""
	}
	return o.Code
}
