// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/etleap/terraform-provider-etleap/internal/sdk/pkg/utils"
	"time"
)

// ConnectionRedshiftStatus - The current status of the connection.
type ConnectionRedshiftStatus string

const (
	ConnectionRedshiftStatusUnknown     ConnectionRedshiftStatus = "UNKNOWN"
	ConnectionRedshiftStatusUp          ConnectionRedshiftStatus = "UP"
	ConnectionRedshiftStatusDown        ConnectionRedshiftStatus = "DOWN"
	ConnectionRedshiftStatusResize      ConnectionRedshiftStatus = "RESIZE"
	ConnectionRedshiftStatusMaintenance ConnectionRedshiftStatus = "MAINTENANCE"
	ConnectionRedshiftStatusQuota       ConnectionRedshiftStatus = "QUOTA"
	ConnectionRedshiftStatusCreating    ConnectionRedshiftStatus = "CREATING"
)

func (e ConnectionRedshiftStatus) ToPointer() *ConnectionRedshiftStatus {
	return &e
}

func (e *ConnectionRedshiftStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "UNKNOWN":
		fallthrough
	case "UP":
		fallthrough
	case "DOWN":
		fallthrough
	case "RESIZE":
		fallthrough
	case "MAINTENANCE":
		fallthrough
	case "QUOTA":
		fallthrough
	case "CREATING":
		*e = ConnectionRedshiftStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ConnectionRedshiftStatus: %v", v)
	}
}

type ConnectionRedshiftDefaultUpdateSchedule struct {
	// The pipeline mode refers to how the pipeline fetches data changes from the source and how those changes are applied to the destination table. See <a target="_blank" href="https://docs.etleap.com/docs/documentation/ZG9jOjIyMjE3ODA2-introduction">the documentation</a> for more details.
	PipelineMode *PipelineUpdateModes `json:"pipelineMode,omitempty"`
	// The update schedule defines when Etleap should automatically check the source for new data. See <a href= "https://support.etleap.com/hc/en-us/articles/360019768853-What-is-the-difference-between-a-Refresh-and-an-Update-" target="_blank" rel="noopener">Updates &amp; Refreshes</a> for more information. When undefined, the pipeline will default to the schedule set on the source connection.
	UpdateSchedule *UpdateScheduleTypes `json:"updateSchedule,omitempty"`
}

func (o *ConnectionRedshiftDefaultUpdateSchedule) GetPipelineMode() *PipelineUpdateModes {
	if o == nil {
		return nil
	}
	return o.PipelineMode
}

func (o *ConnectionRedshiftDefaultUpdateSchedule) GetUpdateSchedule() *UpdateScheduleTypes {
	if o == nil {
		return nil
	}
	return o.UpdateSchedule
}

func (o *ConnectionRedshiftDefaultUpdateSchedule) GetUpdateScheduleMonthly() *UpdateScheduleModeMonthly {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeMonthly
	}
	return nil
}

func (o *ConnectionRedshiftDefaultUpdateSchedule) GetUpdateScheduleHourly() *UpdateScheduleModeHourly {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeHourly
	}
	return nil
}

func (o *ConnectionRedshiftDefaultUpdateSchedule) GetUpdateScheduleInterval() *UpdateScheduleModeInterval {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeInterval
	}
	return nil
}

func (o *ConnectionRedshiftDefaultUpdateSchedule) GetUpdateScheduleDaily() *UpdateScheduleModeDaily {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeDaily
	}
	return nil
}

func (o *ConnectionRedshiftDefaultUpdateSchedule) GetUpdateScheduleWeekly() *UpdateScheduleModeWeekly {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeWeekly
	}
	return nil
}

type ConnectionRedshiftType string

const (
	ConnectionRedshiftTypeRedshift ConnectionRedshiftType = "REDSHIFT"
)

func (e ConnectionRedshiftType) ToPointer() *ConnectionRedshiftType {
	return &e
}

func (e *ConnectionRedshiftType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "REDSHIFT":
		*e = ConnectionRedshiftType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ConnectionRedshiftType: %v", v)
	}
}

// ConnectionRedshift - Specifies the location of a database.
type ConnectionRedshift struct {
	// The current status of the connection.
	Status ConnectionRedshiftStatus `json:"status"`
	// The unique name of this connection.
	Name string `json:"name"`
	// The date and time when then the connection was created.
	CreateDate time.Time `json:"createDate"`
	// When an update schedule is not defined for a connection, the default schedule is used. The default defined individually per `pipelineMode` and may be subject to change.
	DefaultUpdateSchedule []ConnectionRedshiftDefaultUpdateSchedule `json:"defaultUpdateSchedule"`
	// Whether this connection has been marked as active.
	Active bool                   `json:"active"`
	Type   ConnectionRedshiftType `json:"type"`
	// The unique identifier of the connection.
	ID string `json:"id"`
	// The update schedule defines when Etleap should automatically check the source for new data. See <a href= "https://support.etleap.com/hc/en-us/articles/360019768853-What-is-the-difference-between-a-Refresh-and-an-Update-" target="_blank" rel="noopener">Updates &amp; Refreshes</a> for more information. When undefined, the pipeline will default to the schedule set on the source connection.
	UpdateSchedule *UpdateScheduleTypes `json:"updateSchedule,omitempty"`
	// The id of another Etleap Redshift connection. If specified, Etleap will make the data loaded available to the other cluster via Redshift Data Sharing.
	DataSharingDestinations []string `json:"dataSharingDestinations,omitempty"`
	// Should Etleap prefix each load query with metadata? More info can be found <a href="https://docs.etleap.com/docs/documentation/ba7744fcf6114-redshift-optional-connection-settings#include-query-tags">here</a>.
	QueryTagsEnabled *bool `default:"false" json:"queryTagsEnabled"`
	// When Etleap creates Redshift tables, SELECT privileges will be granted to user groups specified here.
	UserGroups []string `json:"userGroups,omitempty"`
	// Are you going to use this connection only as a source for pipelines? When `true`, this connection will only be available as an ETL source only, and Etleap will skip the creation of an audit table in the database.
	SourceOnly *bool `default:"false" json:"sourceOnly"`
	// Etleap will create VARCHAR columns with the minimal required width based on the data it's loading, and expand the column width as required. This can improve performance but there are <a target="_blank" href="https://docs.etleap.com/docs/documentation/ba7744fcf6114-redshift-optional-connection-settings#enable-dynamic-varchar-widths">some limitations</a>. Note: if set to `true`, it can't later be updated to `false`.
	DynamicVarcharWidthEnabled *bool `default:"false" json:"dynamicVarcharWidthEnabled"`
	// If not specified, the default schema will be used.
	//
	// Deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
	Schema    *string    `json:"schema,omitempty"`
	Username  string     `json:"username"`
	SSHConfig *SSHConfig `json:"sshConfig,omitempty"`
	Port      int64      `json:"port"`
	Address   string     `json:"address"`
	Database  string     `json:"database"`
}

func (c ConnectionRedshift) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConnectionRedshift) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ConnectionRedshift) GetStatus() ConnectionRedshiftStatus {
	if o == nil {
		return ConnectionRedshiftStatus("")
	}
	return o.Status
}

func (o *ConnectionRedshift) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ConnectionRedshift) GetCreateDate() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreateDate
}

func (o *ConnectionRedshift) GetDefaultUpdateSchedule() []ConnectionRedshiftDefaultUpdateSchedule {
	if o == nil {
		return []ConnectionRedshiftDefaultUpdateSchedule{}
	}
	return o.DefaultUpdateSchedule
}

func (o *ConnectionRedshift) GetActive() bool {
	if o == nil {
		return false
	}
	return o.Active
}

func (o *ConnectionRedshift) GetType() ConnectionRedshiftType {
	if o == nil {
		return ConnectionRedshiftType("")
	}
	return o.Type
}

func (o *ConnectionRedshift) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ConnectionRedshift) GetUpdateSchedule() *UpdateScheduleTypes {
	if o == nil {
		return nil
	}
	return o.UpdateSchedule
}

func (o *ConnectionRedshift) GetUpdateScheduleMonthly() *UpdateScheduleModeMonthly {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeMonthly
	}
	return nil
}

func (o *ConnectionRedshift) GetUpdateScheduleHourly() *UpdateScheduleModeHourly {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeHourly
	}
	return nil
}

func (o *ConnectionRedshift) GetUpdateScheduleInterval() *UpdateScheduleModeInterval {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeInterval
	}
	return nil
}

func (o *ConnectionRedshift) GetUpdateScheduleDaily() *UpdateScheduleModeDaily {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeDaily
	}
	return nil
}

func (o *ConnectionRedshift) GetUpdateScheduleWeekly() *UpdateScheduleModeWeekly {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeWeekly
	}
	return nil
}

func (o *ConnectionRedshift) GetDataSharingDestinations() []string {
	if o == nil {
		return nil
	}
	return o.DataSharingDestinations
}

func (o *ConnectionRedshift) GetQueryTagsEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.QueryTagsEnabled
}

func (o *ConnectionRedshift) GetUserGroups() []string {
	if o == nil {
		return nil
	}
	return o.UserGroups
}

func (o *ConnectionRedshift) GetSourceOnly() *bool {
	if o == nil {
		return nil
	}
	return o.SourceOnly
}

func (o *ConnectionRedshift) GetDynamicVarcharWidthEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.DynamicVarcharWidthEnabled
}

func (o *ConnectionRedshift) GetSchema() *string {
	if o == nil {
		return nil
	}
	return o.Schema
}

func (o *ConnectionRedshift) GetUsername() string {
	if o == nil {
		return ""
	}
	return o.Username
}

func (o *ConnectionRedshift) GetSSHConfig() *SSHConfig {
	if o == nil {
		return nil
	}
	return o.SSHConfig
}

func (o *ConnectionRedshift) GetPort() int64 {
	if o == nil {
		return 0
	}
	return o.Port
}

func (o *ConnectionRedshift) GetAddress() string {
	if o == nil {
		return ""
	}
	return o.Address
}

func (o *ConnectionRedshift) GetDatabase() string {
	if o == nil {
		return ""
	}
	return o.Database
}

// ConnectionRedshiftInput - Specifies the location of a database.
type ConnectionRedshiftInput struct {
	// The unique name of this connection.
	Name string                 `json:"name"`
	Type ConnectionRedshiftType `json:"type"`
	// The update schedule defines when Etleap should automatically check the source for new data. See <a href= "https://support.etleap.com/hc/en-us/articles/360019768853-What-is-the-difference-between-a-Refresh-and-an-Update-" target="_blank" rel="noopener">Updates &amp; Refreshes</a> for more information. When undefined, the pipeline will default to the schedule set on the source connection.
	UpdateSchedule *UpdateScheduleTypes `json:"updateSchedule,omitempty"`
	// The id of another Etleap Redshift connection. If specified, Etleap will make the data loaded available to the other cluster via Redshift Data Sharing.
	DataSharingDestinations []string `json:"dataSharingDestinations,omitempty"`
	// Should Etleap prefix each load query with metadata? More info can be found <a href="https://docs.etleap.com/docs/documentation/ba7744fcf6114-redshift-optional-connection-settings#include-query-tags">here</a>.
	QueryTagsEnabled *bool `default:"false" json:"queryTagsEnabled"`
	// When Etleap creates Redshift tables, SELECT privileges will be granted to user groups specified here.
	UserGroups []string `json:"userGroups,omitempty"`
	// Are you going to use this connection only as a source for pipelines? When `true`, this connection will only be available as an ETL source only, and Etleap will skip the creation of an audit table in the database.
	SourceOnly *bool `default:"false" json:"sourceOnly"`
	// Etleap will create VARCHAR columns with the minimal required width based on the data it's loading, and expand the column width as required. This can improve performance but there are <a target="_blank" href="https://docs.etleap.com/docs/documentation/ba7744fcf6114-redshift-optional-connection-settings#enable-dynamic-varchar-widths">some limitations</a>. Note: if set to `true`, it can't later be updated to `false`.
	DynamicVarcharWidthEnabled *bool `default:"false" json:"dynamicVarcharWidthEnabled"`
	// If not specified, the default schema will be used.
	//
	// Deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
	Schema    *string    `json:"schema,omitempty"`
	Username  string     `json:"username"`
	SSHConfig *SSHConfig `json:"sshConfig,omitempty"`
	Password  string     `json:"password"`
	Port      int64      `json:"port"`
	Address   string     `json:"address"`
	Database  string     `json:"database"`
}

func (c ConnectionRedshiftInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConnectionRedshiftInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ConnectionRedshiftInput) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ConnectionRedshiftInput) GetType() ConnectionRedshiftType {
	if o == nil {
		return ConnectionRedshiftType("")
	}
	return o.Type
}

func (o *ConnectionRedshiftInput) GetUpdateSchedule() *UpdateScheduleTypes {
	if o == nil {
		return nil
	}
	return o.UpdateSchedule
}

func (o *ConnectionRedshiftInput) GetUpdateScheduleMonthly() *UpdateScheduleModeMonthly {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeMonthly
	}
	return nil
}

func (o *ConnectionRedshiftInput) GetUpdateScheduleHourly() *UpdateScheduleModeHourly {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeHourly
	}
	return nil
}

func (o *ConnectionRedshiftInput) GetUpdateScheduleInterval() *UpdateScheduleModeInterval {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeInterval
	}
	return nil
}

func (o *ConnectionRedshiftInput) GetUpdateScheduleDaily() *UpdateScheduleModeDaily {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeDaily
	}
	return nil
}

func (o *ConnectionRedshiftInput) GetUpdateScheduleWeekly() *UpdateScheduleModeWeekly {
	if v := o.GetUpdateSchedule(); v != nil {
		return v.UpdateScheduleModeWeekly
	}
	return nil
}

func (o *ConnectionRedshiftInput) GetDataSharingDestinations() []string {
	if o == nil {
		return nil
	}
	return o.DataSharingDestinations
}

func (o *ConnectionRedshiftInput) GetQueryTagsEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.QueryTagsEnabled
}

func (o *ConnectionRedshiftInput) GetUserGroups() []string {
	if o == nil {
		return nil
	}
	return o.UserGroups
}

func (o *ConnectionRedshiftInput) GetSourceOnly() *bool {
	if o == nil {
		return nil
	}
	return o.SourceOnly
}

func (o *ConnectionRedshiftInput) GetDynamicVarcharWidthEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.DynamicVarcharWidthEnabled
}

func (o *ConnectionRedshiftInput) GetSchema() *string {
	if o == nil {
		return nil
	}
	return o.Schema
}

func (o *ConnectionRedshiftInput) GetUsername() string {
	if o == nil {
		return ""
	}
	return o.Username
}

func (o *ConnectionRedshiftInput) GetSSHConfig() *SSHConfig {
	if o == nil {
		return nil
	}
	return o.SSHConfig
}

func (o *ConnectionRedshiftInput) GetPassword() string {
	if o == nil {
		return ""
	}
	return o.Password
}

func (o *ConnectionRedshiftInput) GetPort() int64 {
	if o == nil {
		return 0
	}
	return o.Port
}

func (o *ConnectionRedshiftInput) GetAddress() string {
	if o == nil {
		return ""
	}
	return o.Address
}

func (o *ConnectionRedshiftInput) GetDatabase() string {
	if o == nil {
		return ""
	}
	return o.Database
}
