// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GrantsWithoutPrivilegeList - A list of grants without privilege on an object
type GrantsWithoutPrivilegeList struct {
	Grants []GrantWithoutPrivilege `json:"grants"`
}

func (o *GrantsWithoutPrivilegeList) GetGrants() []GrantWithoutPrivilege {
	if o == nil {
		return []GrantWithoutPrivilege{}
	}
	return o.Grants
}
