// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RetentionData - Etleap can remove old rows from your destination. This is a summary of the data retention.
type RetentionData struct {
	RetentionByDay RetentionByDay `json:"retentionByDay"`
	// Policy for the automatic deletion of rows in the destination.
	RetentionPolicy *RetentionPolicy `json:"retentionPolicy,omitempty"`
}

func (o *RetentionData) GetRetentionByDay() RetentionByDay {
	if o == nil {
		return RetentionByDay{}
	}
	return o.RetentionByDay
}

func (o *RetentionData) GetRetentionPolicy() *RetentionPolicy {
	if o == nil {
		return nil
	}
	return o.RetentionPolicy
}
