// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type SourceImpactRadiusType string

const (
	SourceImpactRadiusTypeImpactRadius SourceImpactRadiusType = "IMPACT_RADIUS"
)

func (e SourceImpactRadiusType) ToPointer() *SourceImpactRadiusType {
	return &e
}

func (e *SourceImpactRadiusType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "IMPACT_RADIUS":
		*e = SourceImpactRadiusType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SourceImpactRadiusType: %v", v)
	}
}

type SourceImpactRadius struct {
	// The universally unique identifier for the source.
	ConnectionID string                 `json:"connectionId"`
	Type         SourceImpactRadiusType `json:"type"`
	// Notify if we can't extract for `x` hours. Setting it to `null` disables the notification. Defaults to `null`.
	LatencyThreshold *int64 `json:"latencyThreshold,omitempty"`
	// The Impact Radius entity, spelled the same way as in the UI.
	Entity string `json:"entity"`
}

func (o *SourceImpactRadius) GetConnectionID() string {
	if o == nil {
		return ""
	}
	return o.ConnectionID
}

func (o *SourceImpactRadius) GetType() SourceImpactRadiusType {
	if o == nil {
		return SourceImpactRadiusType("")
	}
	return o.Type
}

func (o *SourceImpactRadius) GetLatencyThreshold() *int64 {
	if o == nil {
		return nil
	}
	return o.LatencyThreshold
}

func (o *SourceImpactRadius) GetEntity() string {
	if o == nil {
		return ""
	}
	return o.Entity
}
