// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type SourceQuoraAdsUpdateType string

const (
	SourceQuoraAdsUpdateTypeQuoraAds SourceQuoraAdsUpdateType = "QUORA_ADS"
)

func (e SourceQuoraAdsUpdateType) ToPointer() *SourceQuoraAdsUpdateType {
	return &e
}

func (e *SourceQuoraAdsUpdateType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "QUORA_ADS":
		*e = SourceQuoraAdsUpdateType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SourceQuoraAdsUpdateType: %v", v)
	}
}

type SourceQuoraAdsUpdate struct {
	// Notify if we can't extract for `x` hours. Setting it to `null` disables the notification. Defaults to `null`.
	LatencyThreshold *int64                    `json:"latencyThreshold,omitempty"`
	Type             *SourceQuoraAdsUpdateType `json:"type,omitempty"`
}

func (o *SourceQuoraAdsUpdate) GetLatencyThreshold() *int64 {
	if o == nil {
		return nil
	}
	return o.LatencyThreshold
}

func (o *SourceQuoraAdsUpdate) GetType() *SourceQuoraAdsUpdateType {
	if o == nil {
		return nil
	}
	return o.Type
}
