// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type SourceZoomPhoneUpdateType string

const (
	SourceZoomPhoneUpdateTypeZoomPhone SourceZoomPhoneUpdateType = "ZOOM_PHONE"
)

func (e SourceZoomPhoneUpdateType) ToPointer() *SourceZoomPhoneUpdateType {
	return &e
}

func (e *SourceZoomPhoneUpdateType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ZOOM_PHONE":
		*e = SourceZoomPhoneUpdateType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SourceZoomPhoneUpdateType: %v", v)
	}
}

type SourceZoomPhoneUpdate struct {
	Type *SourceZoomPhoneUpdateType `json:"type,omitempty"`
	// Notify if we can't extract for `x` hours. Setting it to `null` disables the notification. Defaults to `null`.
	LatencyThreshold *int64 `json:"latencyThreshold,omitempty"`
}

func (o *SourceZoomPhoneUpdate) GetType() *SourceZoomPhoneUpdateType {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *SourceZoomPhoneUpdate) GetLatencyThreshold() *int64 {
	if o == nil {
		return nil
	}
	return o.LatencyThreshold
}
