// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type SourceWorkdayReportType string

const (
	SourceWorkdayReportTypeWorkdayReport SourceWorkdayReportType = "WORKDAY_REPORT"
)

func (e SourceWorkdayReportType) ToPointer() *SourceWorkdayReportType {
	return &e
}

func (e *SourceWorkdayReportType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "WORKDAY_REPORT":
		*e = SourceWorkdayReportType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SourceWorkdayReportType: %v", v)
	}
}

type SourceWorkdayReport struct {
	Type SourceWorkdayReportType `json:"type"`
	// The universally unique identifier for the source.
	ConnectionID string `json:"connectionId"`
	// Notify if we can't extract for `x` hours. Setting it to `null` disables the notification. Defaults to `null`.
	LatencyThreshold *int64 `json:"latencyThreshold,omitempty"`
	// The Workday Report name. Spelled the same as Workday UI but all spaces are replaced with underscores.
	Entity string `json:"entity"`
}

func (o *SourceWorkdayReport) GetType() SourceWorkdayReportType {
	if o == nil {
		return SourceWorkdayReportType("")
	}
	return o.Type
}

func (o *SourceWorkdayReport) GetConnectionID() string {
	if o == nil {
		return ""
	}
	return o.ConnectionID
}

func (o *SourceWorkdayReport) GetLatencyThreshold() *int64 {
	if o == nil {
		return nil
	}
	return o.LatencyThreshold
}

func (o *SourceWorkdayReport) GetEntity() string {
	if o == nil {
		return ""
	}
	return o.Entity
}
