// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type SourceDb2ShardedUpdateType string

const (
	SourceDb2ShardedUpdateTypeDb2Sharded SourceDb2ShardedUpdateType = "DB2_SHARDED"
)

func (e SourceDb2ShardedUpdateType) ToPointer() *SourceDb2ShardedUpdateType {
	return &e
}

func (e *SourceDb2ShardedUpdateType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "DB2_SHARDED":
		*e = SourceDb2ShardedUpdateType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SourceDb2ShardedUpdateType: %v", v)
	}
}

type SourceDb2ShardedUpdate struct {
	// Notify if we can't extract for `x` hours. Setting it to `null` disables the notification. Defaults to `null`.
	LatencyThreshold *int64                      `json:"latencyThreshold,omitempty"`
	Type             *SourceDb2ShardedUpdateType `json:"type,omitempty"`
}

func (o *SourceDb2ShardedUpdate) GetLatencyThreshold() *int64 {
	if o == nil {
		return nil
	}
	return o.LatencyThreshold
}

func (o *SourceDb2ShardedUpdate) GetType() *SourceDb2ShardedUpdateType {
	if o == nil {
		return nil
	}
	return o.Type
}
