// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// TeamInput - <!-- theme: warning -->
// > This feature is currently in Beta which means that it is subject to non-backwards-compatible and breaking changes.
type TeamInput struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (o *TeamInput) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *TeamInput) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}
