// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type SnowflakeAuthenticationTypesInput struct {
	KeyPair  *SnowflakeAuthenticationKeyPair  `tfsdk:"key_pair"`
	Password *SnowflakeAuthenticationPassword `tfsdk:"password"`
}
