// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/etleap/terraform-provider-etleap/internal/sdk/pkg/models/shared"
	"net/http"
)

type CreateELASTICSEARCHConnectionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK.
	ConnectionElasticsearch *shared.ConnectionElasticsearch
	// Bad Request
	Errors *shared.Errors
}

func (o *CreateELASTICSEARCHConnectionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateELASTICSEARCHConnectionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateELASTICSEARCHConnectionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateELASTICSEARCHConnectionResponse) GetConnectionElasticsearch() *shared.ConnectionElasticsearch {
	if o == nil {
		return nil
	}
	return o.ConnectionElasticsearch
}

func (o *CreateELASTICSEARCHConnectionResponse) GetErrors() *shared.Errors {
	if o == nil {
		return nil
	}
	return o.Errors
}
