// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/etleap/terraform-provider-etleap/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetGOOGLEADSConnectionRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetGOOGLEADSConnectionRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetGOOGLEADSConnectionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK.
	ConnectionGoogleAds *shared.ConnectionGoogleAds
	// Forbidden. You don't have access to view this connection.
	Errors *shared.Errors
}

func (o *GetGOOGLEADSConnectionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetGOOGLEADSConnectionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetGOOGLEADSConnectionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetGOOGLEADSConnectionResponse) GetConnectionGoogleAds() *shared.ConnectionGoogleAds {
	if o == nil {
		return nil
	}
	return o.ConnectionGoogleAds
}

func (o *GetGOOGLEADSConnectionResponse) GetErrors() *shared.Errors {
	if o == nil {
		return nil
	}
	return o.Errors
}
