// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/etleap/terraform-provider-etleap/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetMICROSOFTLISTSConnectionRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetMICROSOFTLISTSConnectionRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetMICROSOFTLISTSConnectionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK.
	ConnectionMicrosoftLists *shared.ConnectionMicrosoftLists
	// Forbidden. You don't have access to view this connection.
	Errors *shared.Errors
}

func (o *GetMICROSOFTLISTSConnectionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetMICROSOFTLISTSConnectionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetMICROSOFTLISTSConnectionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetMICROSOFTLISTSConnectionResponse) GetConnectionMicrosoftLists() *shared.ConnectionMicrosoftLists {
	if o == nil {
		return nil
	}
	return o.ConnectionMicrosoftLists
}

func (o *GetMICROSOFTLISTSConnectionResponse) GetErrors() *shared.Errors {
	if o == nil {
		return nil
	}
	return o.Errors
}
