// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/etleap/terraform-provider-etleap/internal/sdk/pkg/models/shared"
	"net/http"
)

type UpdateUSERVOICEConnectionRequest struct {
	ID                        string                            `pathParam:"style=simple,explode=false,name=id"`
	ConnectionUservoiceUpdate *shared.ConnectionUservoiceUpdate `request:"mediaType=application/json"`
}

func (o *UpdateUSERVOICEConnectionRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateUSERVOICEConnectionRequest) GetConnectionUservoiceUpdate() *shared.ConnectionUservoiceUpdate {
	if o == nil {
		return nil
	}
	return o.ConnectionUservoiceUpdate
}

type UpdateUSERVOICEConnectionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK.
	ConnectionUservoice *shared.ConnectionUservoice
	// Bad Request
	Errors *shared.Errors
}

func (o *UpdateUSERVOICEConnectionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateUSERVOICEConnectionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateUSERVOICEConnectionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateUSERVOICEConnectionResponse) GetConnectionUservoice() *shared.ConnectionUservoice {
	if o == nil {
		return nil
	}
	return o.ConnectionUservoice
}

func (o *UpdateUSERVOICEConnectionResponse) GetErrors() *shared.Errors {
	if o == nil {
		return nil
	}
	return o.Errors
}
