// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/etleap/terraform-provider-etleap/internal/sdk/pkg/models/shared"
	"net/http"
)

type UpdateTIKTOKADSConnectionRequest struct {
	ID                        string                            `pathParam:"style=simple,explode=false,name=id"`
	ConnectionTikTokAdsUpdate *shared.ConnectionTikTokAdsUpdate `request:"mediaType=application/json"`
}

func (o *UpdateTIKTOKADSConnectionRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateTIKTOKADSConnectionRequest) GetConnectionTikTokAdsUpdate() *shared.ConnectionTikTokAdsUpdate {
	if o == nil {
		return nil
	}
	return o.ConnectionTikTokAdsUpdate
}

type UpdateTIKTOKADSConnectionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK.
	ConnectionTikTokAds *shared.ConnectionTikTokAds
	// Bad Request
	Errors *shared.Errors
}

func (o *UpdateTIKTOKADSConnectionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateTIKTOKADSConnectionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateTIKTOKADSConnectionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateTIKTOKADSConnectionResponse) GetConnectionTikTokAds() *shared.ConnectionTikTokAds {
	if o == nil {
		return nil
	}
	return o.ConnectionTikTokAds
}

func (o *UpdateTIKTOKADSConnectionResponse) GetErrors() *shared.Errors {
	if o == nil {
		return nil
	}
	return o.Errors
}
